stages:
- build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

base:
  stage: build
  image: docker:19.03.1
  services:
  - docker:19.03.0-dind
  before_script:
  - docker info
  - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
  - docker build --target go_base -t registry.gitlab.com/micro-buzz/golang-can:base .
  - docker push registry.gitlab.com/micro-buzz/golang-can

proto:
  stage: build
  image: docker:19.03.1
  services:
  - docker:19.03.0-dind
  before_script:
  - docker info
  - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
  - docker build --target protoc -t registry.gitlab.com/micro-buzz/golang-can:proto .
  - docker push registry.gitlab.com/micro-buzz/golang-can

npm:
  stage: build
  image: docker:19.03.1
  services:
  - docker:19.03.0-dind
  before_script:
  - docker info
  - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
  - docker build --target vue -t registry.gitlab.com/micro-buzz/golang-can:vue .
  - docker push registry.gitlab.com/micro-buzz/golang-can  